### ISSUE TITLE
Synchronization

### ISSUE THREAD

**Issue by distantrainbow** [epicarchitect/epictodolist#1]
Hello,
Is there a plan for implementing sync through some account? Google, for instance.
It could be very sad to lose a developed hero when phone gets lost our damaged.

**Comment by epicarchitect** [comment]
@distantrainbow hello, at the moment I do not plan any development of this application. But the application has a function for transferring data. In the settings, you can export all your data and also import it to another phone as a json file.

**Comment by epicarchitect** [comment]
I am currently working on this project: https://github.com/epicarchitect/breakbadhabits

**Comment by distantrainbow** [comment]
Data transfer is great if your phone exchange is planned. If phone breaks unexpectedly, you can't transfer any data:)
But your answer is completely legit. Thanks for the great app, as it is.
