### ISSUE TITLE
How do you remove all of the microtransactions and purchase the app?

### ISSUE THREAD

**Issue by JRDK92** [epicarchitect/epictodolist#2]
I really don't like the idea that you have to get coins or gems by watching videos and ads. Like what if I just want to use the app and purchase it outright? It seems like there is no way to do this? You literally just have to watch a bunch of pointless ads for hours just to get everything that's in the app? Like seriously?

**Comment by epicarchitect** [comment]
Nope, the app is designed to be ad-free.  Crystals can be obtained for
achievements.  They will be enough for exactly all the items that you can
buy.  This was the idea of ​​gamification. However, if you still want to
get everything at once, you can change the name of your hero to "creator"
and then you will have enough crystals and coins to buy everything.

чт, 4 мая 2023 г., 00:08 jsaue003 ***@***.***>:

**Comment by JRDK92** [comment]
> 

Thanks. I understand now.
